### ISSUE TITLE
Inquiry Regarding a Missing Image Repository: public.ecr.aws/u2g6w7p2/eks-workshop-demo

### ISSUE THREAD

**Issue by kimkuan** [aws-samples/istio-on-eks#110]
Hello,

I am currently testing Istio on AWS EKS and have encountered an issue with the image repository specified in [values.yaml.](https://github.com/aws-samples/istio-on-eks/blob/main/modules/01-getting-started/values.yaml)

It appears that the image `public.ecr.aws/u2g6w7p2/eks-workshop-demo/~` is no longer available.
Could you please let me know if this image repository has been renamed, moved, or if the image has been deprecated and replaced with a new one?

Your assistance in resolving this matter would be greatly appreciated, as I am keen to complete the demo.

Thank you for your time and assistance.

**Comment by vchintal** [comment]
For the moment please use the following `istio-on-eks/modules/01-getting-started/values.yaml`

```yaml
# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

catalogdetail1:
  image:
    repository: public.ecr.aws/u0x7j7d5/istio-on-eks/catalog_detail
    tag: "1.0"

catalogdetail2:
  image:
    repository: public.ecr.aws/u0x7j7d5/istio-on-eks/catalog_detail
    tag: "2.0"

productcatalog:
  image:
    repository: public.ecr.aws/u0x7j7d5/istio-on-eks/product_catalog
    tag: "1.0"

  env:
    - name: AGG_APP_URL
      value: "http://catalogdetail.workshop.svc.cluster.local:3000/catalogDetail"

frontend:
  image:
    repository: public.ecr.aws/u0x7j7d5/istio-on-eks/frontend_node
    tag: "2.0"

  env:
    - name: BASE_URL
      value: "http://productcatalog.workshop.svc.cluster.local:5000/products/"
```
